INSERT INTO plant_categories (name) VALUES
    ('Legumes - pea and bean family'),
    ('Brassicas - cabbage family'),
    ('Alliums - onion family'),
    ('Cucurbits - cucumber family'),
    ('Umbellifers - carrot family'),
    ('Beet family'),
    ('Leafy salad crops'),
    ('Solanums, basil, and sweetcorn'),
    ('Perennial vegetables');

INSERT INTO plant_catalogue (name, variety, description, category_id, seed_to_harvest, sowing_to_transplant, position, spacing, hardiness, sowing_windows, transplant_windows, harvest_windows, source)
VALUES
-- Legumes
  ('Broad Beans', NULL, NULL, (SELECT id FROM plant_categories WHERE name = 'Legumes - pea and bean family'), '4 months (from late winter and spring sowings)', '4-6 weeks after sowing, when they are about 5-7cm tall', 'Adaptable, will tolerate shade', '20-25 cm equidistant or 15cm apart with 45cm between rows', 'Fully hardy, but can be adversely affect by a long cold spell', '[{"start": "01-01", "end": "04-30"}, {"start": "10-15", "end": "10-31"}]', '[{"start": "02-01", "end": "05-31"}, {"start": "12-01", "end": "12-31"}]', '[{"start": "06-01", "end": "08-15"}]', 'No Dig'),
  ('Climbing Beans', NULL, NULL, (SELECT id FROM plant_categories WHERE name = 'Legumes - pea and bean family'), '3 months for pods, 4-5 for beans', '2-3 weeks', 'Full sun, can tolerate some shade. Avoid a windy position.', '30cm apart, 60cm between rows', 'Killed by frost and need warmth to thrive', '[{"start": "05-15", "end": "06-30"}]', '[{"start": "06-01", "end": "07-15"}]', '[{"start": "07-15", "end": "10-15"}]', 'No Dig'),
  ('Dwarf French Beans', NULL, NULL, (SELECT id FROM plant_categories WHERE name = 'Legumes - pea and bean family'), '2.5 months', '3 weeks', 'Full sun and warmth', '30-35cm apart each way', 'Not hardy. They will be killed by frost.', '[{"start": "05-01", "end": "06-30"}]', '[{"start": "05-15", "end": "07-31"}]', '[{"start": "06-15", "end": "10-15"}]', 'No Dig'),
  ('Peas', NULL, NULL, (SELECT id FROM plant_categories WHERE name = 'Legumes - pea and bean family'), '3-3.5 months', '3 weeks', 'Full sun, moist soil, align rows at 90º to prevailing wind', 'Dwarf varieties: 15cm apart with 30cm between rows across bed. Medium varieties: Double row 30cm apart along length of bed, with plants 20cm apart, or single rows across bed 45cm apart with 20cm between plants. Tall varieties: Single row along length of bed with plants 15cm apart.', 'Hardy, to around -5ºC', '[{"start": "02-15", "end": "04-30"}, {"start": "06-15", "end": "06-30"}, {"start": "11-01", "end": "11-30"}]', '[{"start": "02-01", "end": "05-15"}, {"start": "07-15", "end": "07-31"}]', '[{"start": "06-01", "end": "07-31"}, {"start": "10-01", "end": "10-31"}]', 'No Dig'),
-- Brassicas
  ('Broccoli', NULL, NULL, (SELECT id FROM plant_categories WHERE name = 'Brassicas - cabbage family'), NULL, NULL, NULL, NULL, NULL, '[{"start": "02-15", "end": "07-31"}]', NULL, '[{"start": "03-01", "end": "11-30"}]', 'No Dig'),
  ('Broccoli', 'Calabrese', NULL, (SELECT id FROM plant_categories WHERE name = 'Brassicas - cabbage family'), '3 months', '3-5 weeks', 'Adaptable, tolerates shade', '30-40cm', 'Hardy to approx. -3°C', '[{"start": "02-15", "end": "06-15"}]', '[{"start": "03-15", "end": "08-15"}]', '[{"start": "06-15", "end": "10-15"}]', 'No Dig'),
  ('Broccoli', 'Purple Sprouting', NULL, (SELECT id FROM plant_categories WHERE name = 'Brassicas - cabbage family'), '9 months', '3-5 weeks', 'Adaptable, tolerates shade', '50-60cm', 'Very hardy to approx. -10°C', '[{"start": "04-15", "end": "06-15"}]', '[{"start": "05-15", "end": "07-15"}]', '[{"start": "08-01", "end": "05-15"}]', 'No Dig'),
  ('Broccoli', 'Kaibroc', NULL, (SELECT id FROM plant_categories WHERE name = 'Brassicas - cabbage family'), '2 1/2 months', '3-5 weeks', 'Adaptable, tolerates shade', '30-40cm', 'Shoots hardy to approx. -3°C, plants to -6°C', '[{"start": "04-01", "end": "05-31"}, {"start": "07-01", "end": "07-31"}]', '[{"start": "05-01", "end": "05-31"}, {"start": "08-01", "end": "08-31"}]', '[{"start": "07-01", "end": "11-30"}]', 'No Dig'),
  ('Brussels Sprouts', NULL, 'Suitable for interplanting', (SELECT id FROM plant_categories WHERE name = 'Brassicas - cabbage family'), '5-7 months', '6-8 weeks', 'Any position, including shade. Will tolerate wind', '60cm equidistant', 'Very hardy', '[{"start": "04-15", "end": "05-15"}]', '[{"start": "05-15", "end": "06-30"}]', '[{"start": "10-01", "end": "01-31"}, {"start": "12-01", "end": "03-31"}]', 'No Dig'),
  ('Cabbage', NULL, NULL, (SELECT id FROM plant_categories WHERE name = 'Brassicas - cabbage family'), NULL, NULL, NULL, NULL, NULL, '[{"start": "02-15", "end": "08-31"}]', NULL, '[{"start": "01-01", "end": "12-31"}]', 'No Dig'),
  ('Cabbage', 'Spring', 'Suitable for second follow-on planting', (SELECT id FROM plant_categories WHERE name = 'Brassicas - cabbage family'), '7-8 months', '4-6 weeks', 'Tolerates some shade', '20-30cm', 'Fully hardy. Tight hearts can split below about -5°C', '[{"start": "08-15", "end": "08-31"}]', '[{"start": "09-15", "end": "10-31"}]', '[{"start": "03-15", "end": "05-15"}]', 'No Dig'),
  ('Cabbage', 'Summer', NULL, (SELECT id FROM plant_categories WHERE name = 'Brassicas - cabbage family'), '4 months', '4-6 weeks', 'Tolerates some shade', '35-40cm', 'Fully hardy', '[{"start": "02-15", "end": "03-31"}]', '[{"start": "04-01", "end": "05-31"}]', '[{"start": "06-01", "end": "07-31"}]', 'No Dig'),
  ('Cabbage', 'Autumn', NULL, (SELECT id FROM plant_categories WHERE name = 'Brassicas - cabbage family'), '4 months', '4-6 weeks', 'Tolerates some shade', '45-60cm', 'Fully hardy. Tight hearts can split below -5°C', '[{"start": "04-15", "end": "05-15"}]', '[{"start": "05-01", "end": "06-30"}]', '[{"start": "09-01", "end": "11-30"}]', 'No Dig'),
  ('Cabbage', 'Winter', 'Suitable for second follow-on planting', (SELECT id FROM plant_categories WHERE name = 'Brassicas - cabbage family'), '5 months', '4-6 weeks', 'Tolerates some shade', '40cm', 'Fully hardy', '[{"start": "06-01", "end": "06-31"}]', '[{"start": "07-01", "end": "07-31"}]', '[{"start": "11-01", "end": "03-31"}]', 'No Dig'),
  ('Cauliflower', NULL, 'Suitable for interplanting in late summer', (SELECT id FROM plant_categories WHERE name = 'Brassicas - cabbage family'), '4 months (summer and autumn crop), 8 months (early spring crop)', '4-6 weeks', 'Any position, tolerates some shade', '40-55cm equidistant', 'Hardy to -10°C in leaf and -5°C for curds', '[{"start": "02-15", "end": "03-15"}, {"start": "06-15", "end": "06-30"}, {"start": "07-15", "end": "08-31"}]', '[{"start": "04-01", "end": "04-15"}, {"start": "09-01", "end": "09-15"}]', '[{"start": "03-01", "end": "05-15"}, {"start": "06-15", "end": "07-15"}, {"start": "10-01", "end": "11-30"}]', 'No Dig'),
  ('Kale', NULL, 'Suitable as a follow on crop', (SELECT id FROM plant_categories WHERE name = 'Brassicas - cabbage family'), '2-3 months', '3-6 weeks', 'Full sun is ideal, but will tolerate some shade', '45-50cm for large varieties, 35cm for dwarf varieties, 22cm for salad leaves', 'Very hardy, down to at least -10°C', '[{"start": "03-01", "end": "04-30"}, {"start": "05-15", "end": "06-30"}, {"start": "07-15", "end": "08-15"}]', '[{"start": "04-01", "end": "09-15"}]', '[{"start": "06-01", "end": "03-31"}, {"start": "10-01", "end": "04-30"}]', 'No Dig'),
  ('Radish', 'Spring', 'Suitable for multisowing and as a second or third crop', (SELECT id FROM plant_categories WHERE name = 'Brassicas - cabbage family'), '6 weeks', '3-4 weeks', 'Full sun or some shade', 'Multisown 15cm equidistant', 'Moderately hardy', '[{"start": "02-15", "end": "04-30"}]', '[{"start": "03-15", "end": "05-15"}]', '[{"start": "04-01", "end": "06-15"}]', 'No Dig'),
  ('Radish', 'Winter', 'Suitable as a follow-on crop', (SELECT id FROM plant_categories WHERE name = 'Brassicas - cabbage family'), '3 months', '3-4 weeks', 'Full sun or some shade', '20cm equidistant', 'Moderately hardy, down to -4°C', '[{"start": "07-15", "end": "07-31"}]', '[{"start": "08-15", "end": "08-31"}]', '[{"start": "10-01", "end": "01-31"}]', 'No Dig'),
  ('Swede', NULL, 'Suitable as a second follow-on crop', (SELECT id FROM plant_categories WHERE name = 'Brassicas - cabbage family'), '4 months', '4 weeks', 'Full sun or a little shade', '30-35cm equidistant', 'Extremely hardy, to at least -10°C', '[{"start": "05-15", "end": "05-31"}]', '[{"start": "06-15", "end": "06-30"}]', '[{"start": "10-01", "end": "03-31"}]', 'No Dig'),
  ('Turnip', NULL, 'Suitable for multisowing and interplanting', (SELECT id FROM plant_categories WHERE name = 'Brassicas - cabbage family'), '2 months', '2-4 weeks', 'Full sun', '25-30cm equidistant', 'Hardy to approx. -5°C', '[{"start": "02-15", "end": "03-15"}, {"start": "08-01", "end": "08-15"}]', '[{"start": "03-15", "end": "04-15"}, {"start": "08-15", "end": "08-31"}]', '[{"start": "05-01", "end": "06-15"}, {"start": "10-01", "end": "11-15"}]', 'No Dig');
